version: '3'

services:
  db:
    container_name: get_usdt_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - get_usdt_network
    ports:
      - "5432:${DB_PORT}"

networks:
  get_usdt_network:
    external: true